export { default as Lista } from '@/pages/dashboard/FormulariosC/Lista'
export { default as Crear } from '@/pages/dashboard/FormulariosC/Crear'
export { default as Errores_Test } from '@/pages/dashboard/FormulariosC/Errores_Test'
export { default as Participantes } from '@/pages/dashboard/FormulariosC/Participantes'
export { default as SeleccionarSecciones } from '@/pages/dashboard/FormulariosC/SeleccionarSecciones'
export { default as AddSeccion } from '@/pages/dashboard/FormulariosC/AddSeccion'
